### ISSUE TITLE
Can it be modified to download the ad-free audio instead?

### ISSUE THREAD

**Issue by expwnent** [bipster/harmontown-video-downloader#2]
I'm not demanding you do it for me but it would help a lot if you could point me in the right direction. I don't have enough space to spare for all the video but I don't want ads when I relisten.

**Comment by bipster** [comment]
@expwnent Sorry, I've been kinda holiday-absent!

Can you point me at where the ad-free audio is located?

On https://www.harmontown.com/2019/12/video-episode-360-cliffhanger/ , is "Audio only" the link?

Or is it the "Download Episode" link via https://www.harmontown.com/2019/12/episode-cliffhanger/ ?

They're both mp3s but I don't know which is which, if there's a difference.

**Comment by expwnent** [comment]
The audio only link on the video episode page is the ad-free audio. 99% sure.

**Comment by bipster** [comment]
Awesome, thanks!  I'm planning to add a configuration property by Monday that lets people choose between full-video, low-res video, and the audio.

If you want something sooner than that, these are the relevant lines for a more-focused hack:

https://github.com/bipster/harmontown-video-downloader/blob/master/src/org/bipsterite/DownloadVideos.groovy#L41-L46

i.e. to hack the script to do audio-only:
* line 42 (i.e. how the files are saved locally) needs ".mp4" changed to ".mp3"
* line 45 (i.e. how the download link is found) would need to change so that instead of finding the first "Download" link, you'd want to find the third/last one.  i.e. instead of ".first()", I think it'd work to ".last()", there.

That should be all you've have to do.
